import '@/styles/index.scss';
import type { Metadata } from "next";

// $======================== RootLayout ========================$ //

export const metadata: Metadata = {
  title: "Kekstagram",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className='wrapper'>
          <main>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
